-- 0002_seed_legal_documents.sql
-- Auto-generated by migrations/seed-legal.ts — do not hand-edit.

INSERT INTO legal_documents (kind, version, effective_at, published_at, body_path, body_hash, status)
SELECT 'cgu', '1.0', '2026-05-06', '2026-05-06', 'src/content/legal/cgu-v1.md', '0bd88135c595d7ba1400868fb431d7ec30d684cd9d5000e5fe1454a8d15c195e', 'published'
WHERE NOT EXISTS (SELECT 1 FROM legal_documents WHERE kind = 'cgu' AND version = '1.0');

INSERT INTO legal_documents (kind, version, effective_at, published_at, body_path, body_hash, status)
SELECT 'pdc', '1.0', '2026-05-06', '2026-05-06', 'src/content/legal/pdc-v1.md', '5ade906e1e1df9225f1c6b7ce3742aa8a9b02c7589ca44c0b20fe6c1d933fab9', 'published'
WHERE NOT EXISTS (SELECT 1 FROM legal_documents WHERE kind = 'pdc' AND version = '1.0');

INSERT INTO legal_documents (kind, version, effective_at, published_at, body_path, body_hash, status)
SELECT 'mentions', '1.0', '2026-05-06', '2026-05-06', 'src/content/legal/mentions-v1.md', 'e726640160ca1a4b1b75b9f30a4bc0a9ed49390553af2847aa9e3d3d1c0abffb', 'published'
WHERE NOT EXISTS (SELECT 1 FROM legal_documents WHERE kind = 'mentions' AND version = '1.0');
