-- 0003_publish_legal_v1_1.sql
-- Auto-generated by migrations/seed-legal.ts — do not hand-edit.

-- Retire any prior published cgu before publishing 1.1
UPDATE legal_documents SET status = 'retired'
WHERE kind = 'cgu' AND status = 'published' AND version != '1.1';

INSERT INTO legal_documents (kind, version, effective_at, published_at, body_path, body_hash, status)
SELECT 'cgu', '1.1', '2026-05-06', '2026-05-06', 'src/content/legal/cgu-v1_1.md', 'd4131fe072e279c8b532fa827f61a53cca6043a991611381d3dcb94872c3dd03', 'published'
WHERE NOT EXISTS (SELECT 1 FROM legal_documents WHERE kind = 'cgu' AND version = '1.1');

-- Retire any prior published pdc before publishing 1.1
UPDATE legal_documents SET status = 'retired'
WHERE kind = 'pdc' AND status = 'published' AND version != '1.1';

INSERT INTO legal_documents (kind, version, effective_at, published_at, body_path, body_hash, status)
SELECT 'pdc', '1.1', '2026-05-06', '2026-05-06', 'src/content/legal/pdc-v1_1.md', 'aa51dd6d92b665185fcb75a10ef6fb0257d91200a31d28c60da0394edd7a906a', 'published'
WHERE NOT EXISTS (SELECT 1 FROM legal_documents WHERE kind = 'pdc' AND version = '1.1');

-- Retire any prior published mentions before publishing 1.1
UPDATE legal_documents SET status = 'retired'
WHERE kind = 'mentions' AND status = 'published' AND version != '1.1';

INSERT INTO legal_documents (kind, version, effective_at, published_at, body_path, body_hash, status)
SELECT 'mentions', '1.1', '2026-05-06', '2026-05-06', 'src/content/legal/mentions-v1_1.md', '18ca06335632a84c21e86dc53503dfc6992ac42fb2c9f5705c70ac65f95a58a7', 'published'
WHERE NOT EXISTS (SELECT 1 FROM legal_documents WHERE kind = 'mentions' AND version = '1.1');
