-- 0004_publish_pdc_v1_2.sql
-- Auto-generated by migrations/seed-legal.ts — do not hand-edit.

-- Retire any prior published pdc before publishing 1.2
UPDATE legal_documents SET status = 'retired'
WHERE kind = 'pdc' AND status = 'published' AND version != '1.2';

INSERT INTO legal_documents (kind, version, effective_at, published_at, body_path, body_hash, status)
SELECT 'pdc', '1.2', '2026-05-07', '2026-05-07', 'src/content/legal/pdc-v1_2.md', '3b0c7636d33a52787848d2bf6d7a2d2459d0c41dc4325c9467d6ac17fa3dbb01', 'published'
WHERE NOT EXISTS (SELECT 1 FROM legal_documents WHERE kind = 'pdc' AND version = '1.2');
