-- 0005_publish_mentions_v1_2.sql
-- Auto-generated by migrations/seed-legal.ts — do not hand-edit.

-- Retire any prior published mentions before publishing 1.2
UPDATE legal_documents SET status = 'retired'
WHERE kind = 'mentions' AND status = 'published' AND version != '1.2';

INSERT INTO legal_documents (kind, version, effective_at, published_at, body_path, body_hash, status)
SELECT 'mentions', '1.2', '2026-05-07', '2026-05-07', 'src/content/legal/mentions-v1_2.md', '5799f272f76504d5d1bafa7a790eb34d8e2be7f18e725b595893ba73d4a0fdcc', 'published'
WHERE NOT EXISTS (SELECT 1 FROM legal_documents WHERE kind = 'mentions' AND version = '1.2');
