import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';

/**
 * Generates the legal-document seed migrations:
 *   - 0002_seed_legal_documents.sql      → bootstrap with v1.0 (placeholder)
 *   - 0003_publish_legal_v1_1.sql        → retire v1.0, publish v1.1 (real content)
 *
 * Each new published version should be added as a new entry below and a new
 * migration file emitted with an incremented prefix. Earlier migration files
 * are NEVER re-emitted with different content — that would break the
 * append-only contract enforced by the migration runner (`_migrations` table).
 */

const ROOT = path.resolve(__dirname, '..');
const LEGAL_DIR = path.join(ROOT, 'src', 'content', 'legal');
const MIGRATIONS_DIR = path.join(ROOT, 'migrations');

type LegalKind = 'cgu' | 'pdc' | 'mentions';

interface DocSpec {
  kind: LegalKind;
  version: string;
  file: string; // file name in src/content/legal/
}

interface VersionGroup {
  filename: string; // migration filename
  effective_at: string;
  docs: DocSpec[];
  retirePrior?: boolean;
}

const GROUPS: VersionGroup[] = [
  {
    filename: '0002_seed_legal_documents.sql',
    effective_at: '2026-05-06',
    docs: [
      { kind: 'cgu', version: '1.0', file: 'cgu-v1.md' },
      { kind: 'pdc', version: '1.0', file: 'pdc-v1.md' },
      { kind: 'mentions', version: '1.0', file: 'mentions-v1.md' },
    ],
  },
  {
    filename: '0003_publish_legal_v1_1.sql',
    effective_at: '2026-05-06',
    retirePrior: true,
    docs: [
      { kind: 'cgu', version: '1.1', file: 'cgu-v1_1.md' },
      { kind: 'pdc', version: '1.1', file: 'pdc-v1_1.md' },
      { kind: 'mentions', version: '1.1', file: 'mentions-v1_1.md' },
    ],
  },
  {
    filename: '0004_publish_pdc_v1_2.sql',
    effective_at: '2026-05-07',
    retirePrior: true,
    docs: [{ kind: 'pdc', version: '1.2', file: 'pdc-v1_2.md' }],
  },
  {
    filename: '0005_publish_mentions_v1_2.sql',
    effective_at: '2026-05-07',
    retirePrior: true,
    docs: [{ kind: 'mentions', version: '1.2', file: 'mentions-v1_2.md' }],
  },
];

function sha256(text: string): string {
  return crypto.createHash('sha256').update(text, 'utf8').digest('hex');
}

function emitGroup(group: VersionGroup): void {
  const lines: string[] = [
    `-- ${group.filename}`,
    '-- Auto-generated by migrations/seed-legal.ts — do not hand-edit.',
    '',
  ];

  for (const doc of group.docs) {
    const filePath = path.join(LEGAL_DIR, doc.file);
    const body = fs.readFileSync(filePath, 'utf8');
    const hash = sha256(body);
    const bodyPath = path.relative(ROOT, filePath).replace(/\\/g, '/');

    if (group.retirePrior) {
      lines.push(
        `-- Retire any prior published ${doc.kind} before publishing ${doc.version}`,
        `UPDATE legal_documents SET status = 'retired'`,
        `WHERE kind = '${doc.kind}' AND status = 'published' AND version != '${doc.version}';`,
        ''
      );
    }

    lines.push(
      `INSERT INTO legal_documents (kind, version, effective_at, published_at, body_path, body_hash, status)`,
      `SELECT '${doc.kind}', '${doc.version}', '${group.effective_at}', '${group.effective_at}', '${bodyPath}', '${hash}', 'published'`,
      `WHERE NOT EXISTS (SELECT 1 FROM legal_documents WHERE kind = '${doc.kind}' AND version = '${doc.version}');`,
      ''
    );
  }

  const out = path.join(MIGRATIONS_DIR, group.filename);
  fs.writeFileSync(out, lines.join('\n'), 'utf8');
  console.log(`[seed-legal] wrote ${out}`);
}

for (const group of GROUPS) {
  emitGroup(group);
}
